version: '3'

services:
  db:
    image: library/mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"

  nginx:
    image: nginx
    ports:
    - "8080:80"
    environment:

  siem:
    image: el
